dist: trusty
language: python
sudo: false
env:
    # TRAVIS_PYTHON_VERSION is only needed for neo's setup.py
    # OPENBLAS_NUM_THREADS=1 avoid slowdowns:
    # https://github.com/xianyi/OpenBLAS/issues/731
    global: PYTHON_VERSION=3.6 DISPLAY=:99.0 MNE_LOGGING_LEVEL=warning TEST_LOCATION=src
            PIP_DEPENDENCIES="codecov nitime"
            TRAVIS_PYTHON_VERSION=3.6 CONDA_VERSION=">=4.3.27"
            OPENBLAS_NUM_THREADS=1

matrix:
  include:
    # Linux
    - os: linux
      env: CONDA_ENVIRONMENT="environment.yml"

    # OSX conda
    - os: osx
      env: CONDA_ENVIRONMENT="environment.yml"


branches:
  only:
    - master

cache:
  directories:
  - $HOME/.cache/pip

before_install:
  - deactivate
  - git clone https://github.com/astropy/ci-helpers.git;
  - source ci-helpers/travis/setup_conda.sh;

install:
  - pip install -e .

script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=mne_realtime --pyargs mne_realtime

after_success:
  - cp .coverage $TRAVIS_BUILD_DIR
  - codecov --root $TRAVIS_BUILD_DIR || echo "codecov upload failed"
