dist: trusty
sudo: false

language: python

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.cache/pip

matrix:
  include:
    # Linux
    - os: linux
      env: CONDA_ENVIRONMENT="environment.yml"

    # OSX conda
    - os: osx
      osx_image: xcode8.3
      env: CONDA_ENVIRONMENT="environment.yml"

before_install:
  - deactivate
  - git clone https://github.com/astropy/ci-helpers.git;
  - source ci-helpers/travis/setup_conda.sh;
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        pip install --upgrade pyqt5>=5.10 pylsl;
    fi;

install:
  - pip install -e .

script:
  - mkdir for_test
  - cd for_test
  - pytest -v --cov=mne_realtime --pyargs mne_realtime

after_success:
  - cp .coverage $TRAVIS_BUILD_DIR
  - codecov --root $TRAVIS_BUILD_DIR || echo "codecov upload failed"
