name: mne-realtime
channels:
  - defaults

dependencies:
  - python<3.7
  - pip
  - matplotlib
  - numpy
  - scipy
  - pytest
  - pytest-cov
  - pytest-mock
  - flake8
  - pip:
    - mne
    - pydocstyle
    - pytest-sugar
    - codespell
    - codecov
    - pylsl>=1.12
